Emit TTS event when using global hotkey to toggle voice activation
BearWare/TeamTalk5 pull request #1839
Opened 2023-04-19 19:03 UTC by CoBC

@jeremyp3 This was your request, can you test this?

2023-04-22 17:22 UTC, jeremyp3 commented
ok for me. thanks @CoBC !

2023-05-01 17:48 UTC, bear101 requested changes

2023-05-02 17:44 UTC, bear101 requested changes

2023-05-02 17:44 UTC, bear101 commented on Client/qtTeamTalk/mainwindow.cpp
> +void MainWindow::enableVoiceActivation(bool checked, SoundEvent on, SoundEvent off, bool TTS)
What is the purpose of boolean value "TTS"? I don't see it being used anywhere.

2023-05-02 17:44 UTC, bear101 commented on Client/qtTeamTalk/mainwindow.cpp
> +void MainWindow::enableVoiceActivation(bool checked, SoundEvent on, SoundEvent off, bool TTS)
Can't you change the code so only ui.actionEnableVoiceActivation calls MainWindow::slotMeEnableVoiceActivation() ?

2023-05-02 19:26 UTC, bear101 approved these changes

2023-05-02 19:27 UTC, merged